### ISSUE TITLE
Varios errores en diferentes paginas en Administracion

### ISSUE THREAD

**Issue by fr0st87** [yamilrh/2moons-v2.0#3]
A ver, estuve revisando cada una de las paginas de la administracion, a ver si funcionaban todas. y varias dieron errores, los pondre cada uno en este issues, porque te llenaria de issues esto

Cuando se entra a la pagina de Modulos.

WARNING
Message: Undefined array key "mode"
File: /includes/pages/adm/ShowModulePage.php
Line: 27
URL: http://localhost/2moons-v2.0/admin.php?page=module
PHP-Version: 8.3.11
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/adm/ShowModulePage.php(27): errorHandler()
#1 /admin.php(87): ShowModulePage()
#2 {main}

**Comment by fr0st87** [comment]
Cuando se entra a la pagina de Backup 

WARNING
Message: Undefined array key "action"
File: /includes/pages/adm/ShowDumpPage.php
Line: 26
URL: http://localhost/2moons-v2.0/admin.php?page=dump
PHP-Version: 8.3.11
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/adm/ShowDumpPage.php(26): errorHandler()
#1 /admin.php(203): ShowDumpPage()
#2 {main}

**Comment by fr0st87** [comment]
Cuando se entra a la pagina de Creador


WARNING
Message: Undefined array key "mode"
File: /includes/pages/adm/ShowCreatorPage.php
Line: 27
URL: http://localhost/2moons-v2.0/admin.php?page=create
PHP-Version: 8.3.11
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/adm/ShowCreatorPage.php(27): errorHandler()
#1 /admin.php(99): ShowCreatorPage()
#2 {main}

**Comment by fr0st87** [comment]
Cuando se entra a la pagina de Baneados


WARNING
Message: Undefined array key "order"
File: /includes/pages/adm/ShowBanPage.php
Line: 24
URL: http://localhost/2moons-v2.0/admin.php?page=bans
PHP-Version: 8.3.11
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/adm/ShowBanPage.php(24): errorHandler()
#1 /admin.php(111): ShowBanPage()
#2 {main}

**Comment by fr0st87** [comment]
Cuando se entra a la pagina de Conectados

WARNING
Message: Undefined array key "delete"
File: /includes/pages/adm/ShowSearchPage.php
Line: 24
URL: http://localhost/2moons-v2.0/admin.php?page=search&search=online&minimize=on
PHP-Version: 8.3.11
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/adm/ShowSearchPage.php(24): errorHandler()
#1 /admin.php(139): ShowSearchPage()
#2 {main}

**Comment by fr0st87** [comment]
y bueno me aburrí, son varios... si puedes revisarlos.
